wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    code_path: code/run_train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1663359763.411579
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 3
      - 17
      - 19
      - 23
      - 37
      4: 3.9.12
      5: 0.13.1
      8:
      - 5
ce_weight_clv:
  desc: null
  value: 1
ce_weight_mod:
  desc: null
  value: 1
dropout:
  desc: null
  value: 0.3
embedding_dim:
  desc: null
  value: 1024
encoder_layers:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.0001
mse_weight:
  desc: null
  value: 3
num_heads:
  desc: null
  value: 16
weight_decay:
  desc: null
  value: 0.0001
